{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[WinError 10054] An existing connection was forcibly closed by the remote host","timestamp":"2025-01-16 14:34:21,864+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[WinError 10054] An existing connection was forcibly closed by the remote host","timestamp":"2025-01-16 16:57:19,845+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"Connection to remote host was lost.","timestamp":"2025-01-16 17:04:32,649+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[WinError 10054] An existing connection was forcibly closed by the remote host","timestamp":"2025-01-16 17:05:08,308+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[WinError 10054] An existing connection was forcibly closed by the remote host","timestamp":"2025-01-16 22:06:01,788+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[WinError 10054] An existing connection was forcibly closed by the remote host","timestamp":"2025-01-16 22:06:09,708+0530","service":"FyersDataSocket"}
